### ISSUE TITLE
a little suggestion

### ISSUE THREAD

**Issue by bau720123** [fastrde/phonegap-checkGPS#2]
work perfect in Android and iOS
when in Android and iOS
if detect the GPS setting is "off" => go to the Android's and iOS's setting page (if could，I think it will more humanity)

such like that

```
CheckGPS.go.settingpage ....
```

**Comment by fastrde** [comment]
open the SettingsPage programmatically is not possible between iOS 5.1 and 8.1(?) so it's not an enhancement that behaves the same on both platforms (ios and android) and I won't implement it. sorry.

**Comment by bau720123** [comment]
ok~
thanks @fastrde
