### ISSUE TITLE
cant install with latest version of cordova

### ISSUE THREAD

**Issue by citsys** [fastrde/phonegap-checkGPS#4]
cordova plugin add https://github.com/fastrde/cordova-plugin-fastrde-checkgps.git

Returns exit code 1 failed to fetch plugin via registry, Probabally this is either a connection problem, or plugin spec is incorrect.

**Comment by jensbroecher** [comment]
Have the same issue. I had to remove it.

**Comment by fastrde** [comment]
it's solved by #5
