### ISSUE TITLE
Upgrade cordova-plugin-geolocation

### ISSUE THREAD

**Issue by tujlaky** [fastrde/phonegap-checkGPS#6]

**Comment by tujlaky** [comment]
Current version is 2.4.3 and the plugin uses only 1.0.1.

**Comment by tujlaky** [comment]
I think this can be resolved by merging this pr: https://github.com/fastrde/cordova-plugin-fastrde-checkgps/pull/5

**Comment by MahmoudFawzy** [comment]
u can use this plugin from here https://github.com/MahmoudFawzy/cordova-plugin-fastrde-checkgps.git

**Comment by rolinger** [comment]
@MahmoudFawzy - I forked fastrde too and then saw yours.  However yours does not include a package.json file which is the new format.  

I added it to my fork if anyone wants to use it:
`cordova plugin add https://github.com/rolinger/cordova-plugin-fastrde-checkgps/`

**Comment by fastrde** [comment]
merged the pr. thanks.
